updated release copy script

diff --git a/scripts/cp_images_to_release b/scripts/cp_images_to_release
--- a/scripts/cp_images_to_release
+++ b/scripts/cp_images_to_release
@@ -1,25 +1,24 @@
 #!/bin/bash
 
-# set base destination directory
+# set variables
+ver_num=${1}
 base_src="/opt/live/overclockix"
 base_dest="/mnt/overclockix"
+
+# check for version number
+if [ -z ${ver_num} ]
+then
+	echo "error: you must provide a valid version number for the first argument"
+	echo "example:  ${0} 7.0.0"
+	exit 1
+fi
 
 ### i386_iso-hybrid
 arch="i386"
 img_type="iso-hybrid"
-
-version_dir="${base_dest}/.version_files"
-version_file="${version_dir}/${arch}_${img_type}.ver"
-dest_dir="${base_dest}/${arch}/${img_type}"
+dest_dir="${base_dest}/${arch}"
 
 cd ${base_src}/${arch}_${img_type}
-
-CountVar=`cat ${version_file}`
-CountVar1=`echo "${CountVar} + .001" | bc`
-
-ver_num=${CountVar1}
-echo ${CountVar1} > ${version_file}
-
 echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
 cp binary.hybrid.iso ${dest_dir}/overclockix-${arch}-${ver_num}.iso
 ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso
@@ -28,19 +27,9 @@ ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso
 ### i386_usb-hdd
 arch="i386"
 img_type="usb-hdd"
-
-version_dir="${base_dest}/.version_files"
-version_file="${version_dir}/${arch}_${img_type}.ver"
-dest_dir="${base_dest}/${arch}/${img_type}"
+dest_dir="${base_dest}/${arch}"
 
 cd ${base_src}/${arch}_${img_type}
-
-CountVar=`cat ${version_file}`
-CountVar1=`echo "${CountVar} + .001" | bc`
-
-ver_num=${CountVar1}
-echo ${CountVar1} > ${version_file}
-
 echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
 cp binary.img ${dest_dir}/overclockix-${arch}-${ver_num}.img
 ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.img
@@ -49,19 +38,9 @@ ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.img
 ### amd64_iso-hybrid
 arch="amd64"
 img_type="iso-hybrid"
-
-version_dir="${base_dest}/.version_files"
-version_file="${version_dir}/${arch}_${img_type}.ver"
-dest_dir="${base_dest}/${arch}/${img_type}"
+dest_dir="${base_dest}/${arch}"
 
 cd ${base_src}/${arch}_${img_type}
-
-CountVar=`cat ${version_file}`
-CountVar1=`echo "${CountVar} + .001" | bc`
-
-ver_num=${CountVar1}
-echo ${CountVar1} > ${version_file}
-
 echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
 cp binary.hybrid.iso ${dest_dir}/overclockix-${arch}-${ver_num}.iso
 ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso
@@ -70,19 +49,9 @@ ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso
 ### amd64_usb-hdd
 arch="amd64"
 img_type="usb-hdd"
-
-version_dir="${base_dest}/.version_files"
-version_file="${version_dir}/${arch}_${img_type}.ver"
-dest_dir="${base_dest}/${arch}/${img_type}"
+dest_dir="${base_dest}/${arch}"
 
 cd ${base_src}/${arch}_${img_type}
-
-CountVar=`cat ${version_file}`
-CountVar1=`echo "${CountVar} + .001" | bc`
-
-ver_num=${CountVar1}
-echo ${CountVar1} > ${version_file}
-
 echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
 cp binary.img ${dest_dir}/overclockix-${arch}-${ver_num}.img
 ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.img
